### PR TITLE
Fixes incorrect rate-limit reason in /unscheduled_jobs

### LINKED ISSUE #1356: `/unscheduled_jobs` falsely states "You are currently rate limited on how many jobs you launch per minute."
**Describe the bug**
When accessing `/unscheduled_jobs`, I am consistenly seeing "You are currently rate limited on how many jobs you launch per minute", despite having submitted orders of magnitude fewer jobs than the configured rate limit.

**To Reproduce**
1. Start Cook Scheduler
2. Submit a job that will stay pending (e.g. not enough resources to match it)
3. Run `curl -s -u: "http://localhost:12321/unscheduled_jobs?job={uuid}" | jq`
4. See something like the following:

```
[                                                                                                
  {                                                
    "uuid": "20010911-cb5c-431b-a853-38a876f72a25",
    "reasons": [
      {                                                                                    
        "reason": "You are currently rate limited on how many jobs you launch per minute.",
        "data": {                    
          "max-jobs-per-minute": 5000
        }                                          
      },        
      {                                                       
        "reason": "You have 5 other jobs ahead in the queue.",
        "data": {  
          "jobs": [                                                    
            "20010911-ef9a-4ac1-8cf5-f6bd6065ba42",
            "20010911-0792-4f33-b382-24b82b757fcf",
            "20010911-c2a3-4255-ad22-40f47ca1e2a4",
            "20010911-3033-40b9-a0ad-901589ca87c0",  
            "20010911-2075-4b38-ab0c-468f58b16152"
          ]                                                                                      
        }                                                              
      },         
      {               
        "reason": "The job couldn't be placed on any available hosts.",
        "data": {                                    
          "reasons": [       
            {                     
              "reason": "Not enough cpus available.",
              "host_count": 6     
            }                                                                                                                                                                     
          ]                                                                                      
        }                                                                                                                                                                         
      }                                                          
    ]                                                                                                                                                                             
  }                                                              
]                                                        
```

**Expected behavior**
The `/unscheduled_jobs` endpoint should not state you're getting rate-limited when you're not getting rate-limited.

**Additional context**
The problem seems to be that on the following line:

https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/scheduler/scheduler.clj#L597

we're passing the count of *all* seen jobs to the `atom` that is referenced here:

https://github.com/twosigma/Cook/blob/master/scheduler/src/cook/unscheduled.clj#L155

We should instead be passing only the count of rate-limited jobs.

PR coming soon.

### PR DESCRIPTION
**Pull request by dposada**
## Changes proposed in this PR

- using `user->rate-limit-count` instead of `user->number-jobs` for determining whether to report rate-limiting as a reason why the job is not being scheduled

## Why are we making these changes?

Fixes #1356 

Please see the issue above for more context.

### CODE REVIEW

File: scheduler/src/cook/scheduler/scheduler.clj [hunk 1]
```diff
@@ -594,7 +594,7 @@
              (take num-considerable)
              ; Force this to be taken eagerly so that the log line is accurate.
              (doall))]
-    (swap! pool->user->number-jobs update pool-name (constantly @user->number-jobs))
+    (swap! pool->user->number-jobs update pool-name (constantly @user->rate-limit-count))
```
Comment (shamsimam) [inline scheduler/src/cook/scheduler/scheduler.clj]: Can we please rename `pool->user->number-jobs` to `pool->user->num-rate-limited-jobs`?

**Comment by shamsimam** [comment]
Nitpick: Can we also change https://github.com/twosigma/Cook/blob/59901f25fbcda79af6e682d551e6237270b6c8c6/scheduler/src/cook/unscheduled.clj#L159

to use `pos?` also?

File: scheduler/src/cook/scheduler/scheduler.clj (hunk 1 above)
Comment (dposada) [reply scheduler/src/cook/scheduler/scheduler.clj]: Done, good call
