### PR TITLE
scheduler: Make job name and priority optional in API.

### LINKED ISSUE #268: Make "name" and "priority" in job schema optional
When we schema-ized job, we incorrectly made "name" and "priority" required fields which was a backwards incompatible change. There is no strong reason to make these required and breaking backwards compatibility for it isn't worth it. We should change these back to being optional

### PR DESCRIPTION
**Pull request by mforsyth**
They are still required in the database - if missing from API request, default
values are assigned.

Fixes #268

### CODE REVIEW

File: scheduler/src/cook/mesos/api.clj [hunk 1]
```diff
@@ -198,9 +204,13 @@
   (-> Job
     ;; make max-runtime optional.
     ;; It is *not* optional internally but don't want to force users to set it
+    (dissoc :name)
```
Comment (shamsimam) [inline scheduler/src/cook/mesos/api.clj]: We should have unit tests verifying this behavior change of optional name and priority fields.

Comment (mforsyth) [inline scheduler/src/cook/mesos/api.clj]: @shamsimam done (pushed yesterday)

File: scheduler/test/cook/test/mesos/api.clj [hunk 2]
```diff
@@ -193,6 +193,24 @@
...
+                                :body-params {"jobs" [job-with-defaults]}})
+            get-response (h {:scheme :http
+                             :uri "/rawscheduler"
+                             :authorization/user "mforsyth"
+                             :request-method :get
+                             :query-params {"job" (job-with-defaults "uuid")}})
+            new-job (-> get-response response->body-data first)]
+        (is (= (:status create-response) 201))
+        (is (= (:status get-response) 200))
+        (is (= (new-job "name") "cookjob"))
```
Comment (shamsimam) [inline scheduler/test/cook/test/mesos/api.clj]: Nitpick: we should co-locate all the defaults for job attributes like name, priority, max runtime, etc. This may be done in a separate PR.

**Comment by shamsimam** [comment]
One minor comment, else LGTM
