### PR TITLE
Lift start-up-time out of the /info handler function

### LINKED ISSUE #711: /info endpoint "start-time" value is wrong
The `start-time` value retrieved from the `/info` endpoint is the time of the request rather than the time the server started up. This appears to be a weird "feature" of Liberator/Compojure, where the endpoint specification is re-evaluated on each request: https://github.com/weavejester/compojure/issues/148

### PR DESCRIPTION
**Pull request by DaoWen**
## Changes proposed in this PR

Lift the "start-time" timestamp out of the handler-construction function.

## Why are we making these changes?

The timestamp was being re-evaluated to `now` on each request.

Fixes #711.

### CODE REVIEW

File: scheduler/src/cook/mesos/api.clj [hunk 1]
```diff
@@ -1141,13 +1141,14 @@
...
 
+(def start-up-time (tf/unparse iso-8601-format (t/now)))
+
 (defn cook-info-handler
   "Handler for the /info endpoint"
   [settings]
   (let [auth-middleware (:authorization-middleware settings)
-        auth-scheme (str (or (-> auth-middleware meta :json-value) auth-middleware))
+        auth-scheme (str (or (-> auth-middleware meta :json-value) auth-middleware))]
         ;; We store the start-up time (ISO-8601) for reporting on the /info endpoint
```
Comment (dposada) [inline scheduler/src/cook/mesos/api.clj]: The comment should move up too, no?

Comment (DaoWen) [reply scheduler/src/cook/mesos/api.clj]: Yes, that would probably make sense...
